---
version: '2'

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'

  web:
    build: .
    command: bundle exec shotgun janna.rb --host 0.0.0.0 -p 4567
    volumes:
      - '.:/usr/src'
      - 'data:/data'
    ports:
      - '4567:4567'
    environment:
      RACK_ENV: development
    dns:
      - 10.0.0.10
      - 8.8.8.8
    depends_on:
      - 'redis'

  worker:
    build: .
    command: bundle exec sidekiq -r ./janna.rb
    volumes:
      - '.:/usr/src'
      - 'data:/data'
    environment:
      RACK_ENV: development
    dns:
      - 10.0.0.10
      - 8.8.8.8
    depends_on:
      - 'redis'

volumes:
  data:
