---
version: '2'

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - '6379:6379'

  api:
    image: janna:latest
    ports:
      - '4567:4567'
    environment:
      RACK_ENV: production
    depends_on:
      - 'redis'

  worker:
    image: janna:latest
    command: bundle exec sidekiq -r ./config/environment.rb
    volumes:
      - 'data:/data'
    environment:
      RACK_ENV: production
    depends_on:
      - 'redis'
      - 'api'

volumes:
  data:
